[build]
  command = "npm run build"
  publish = "web/dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = [
    "@tensorflow/tfjs-backend-wasm",
    "@tensorflow/tfjs-converter",
    "@tensorflow/tfjs-core",
    "@vladmandic/human"
  ]
  included_files = [
    "node_modules/@tensorflow/tfjs-backend-wasm/dist/*.wasm",
    "node_modules/@vladmandic/human/dist/human.node.js",
    "node_modules/@vladmandic/human/dist/human.node-wasm.js",
    "node_modules/@vladmandic/human/package.json",
    "node_modules/@vladmandic/human/models/*"
  ]
